name: openbeats

services:
  app:
    build:
      context: .
    container_name: openbeats_server
    restart: unless-stopped
    volumes:
      - ${LIBRARY_PATH}:/data
      - ./openbeats:/opt/openbeats
    ports:
      - '5334:5334'
    env_file:
      - .env
